apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-service-smart-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-service-smart-home
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-service-smart-home
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: service-smart-home
          image: europe-central2-docker.pkg.dev/my-project-91405-345021/smart-home-analytics-repo/service-smart-home:{{IMAGE_VERSION}}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: gke-service-smart-home-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gke-service-smart-home
